# Generated by Django 6.0 on 2025-12-11 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_image', models.TextField()),
                ('original_image', models.TextField()),
                ('control_images', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'Gallery entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
