# Generated by Django 6.0 on 2025-12-12 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_image_path', models.CharField(blank=True, default='', help_text="Path to input image in MinIO (e.g., 'generations/input/abc123.jpg')", max_length=500)),
                ('generated_image_path', models.CharField(blank=True, default='', help_text='Path to generated output image in MinIO', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Generation logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='storage_gen_created_1a98c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ControlImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_path', models.CharField(help_text='Path to control image in MinIO', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Order of this image in the control sequence')),
                ('generation_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_images', to='storage.generationlog')),
            ],
            options={
                'verbose_name_plural': 'Control images',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['generation_log', 'order'], name='storage_con_generat_61f7fe_idx')],
            },
        ),
    ]
