# Generated by Django 6.0 on 2025-12-12 14:16

import storage.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=storage.models.image_file_path)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(default='image/jpeg', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Gallery images',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='storage_gal_created_1c807f_idx')],
            },
        ),
    ]
